name: Construcción y despliegue de una aplicación ASP.NET MVC a Azure

env:
  AZURE_WEBAPP_NAME: upt-awa-349          # Aquí va el nombre de su aplicación
  AZURE_WEBAPP_PACKAGE_PATH: '.'          # Ruta de destino
  DOTNET_VERSION: '8'                     # Versión de .NET

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Restaurar los paquetes
        run: |
          cd src
          dotnet restore

      - name: Ejecutar pruebas con cobertura
        run: |
          cd src
          dotnet test --collect:"XPlat Code Coverage" --settings ../coverlet.runsettings --results-directory ../TestResults

      - name: Generar reporte de cobertura
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.7
        with:
          reports: ./TestResults/**/*.xml
          targetdir: coveragereport
          reporttypes: MarkdownSummary;MarkdownAssembliesSummary;MarkdownSummaryGithub

      - name: Subir reporte de cobertura como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: coveragereport

      - name: Publicar cobertura en resumen del build
        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        shell: bash

      - name: Instalar Scanner de SonarCloud
        run: dotnet tool install -g dotnet-sonarscanner

      - name: Ejecutar análisis de SonarCloud
        run: |
          cd src
          dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Publicar la aplicación localmente
        run: |
          cd src
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/publish

      - name: Subir el artefacto para el job de despliegue
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/publish

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Descargar el artefacto del job de construcción
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Desplegar en Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          restart: true
